apiVersion: v1
kind: PersistentVolume
metadata:
  name: wdt-test-static-pv
  namespace: wdt-test
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: wdt-test-fast
  local:
    path: /www/wdt-test/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - izm5efs4sbjrz6mm7yrhqzz
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wdt-test-static-pvc
  namespace: wdt-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: wdt-test-fast
