apiVersion: v1
kind: PersistentVolume
metadata:
  name: vtsc-test-lr-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vtsc-test-fast
  local:
    path: /root/k8s/vtsc-test/localResource/vtscfiles
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - izm5efs4sbjrz6mm7yrhqzz
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vtsc-test-lr-pvc
  namespace: vtsc-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: vtsc-test-fast
