global:
  hosts:
    domain: banajava.com
    hostSuffix: git
    https: false
certmanager-issuer:
  email: liuwenjiegod@126.com
prometheus:
  install: false
gitlab-runner:
  install: false
nginx-ingress:
  install: false
postgresql:
  persistence:
    storageClass: alicloud-nas
    size: 8Gi
minio:
  persistence:
    storageClass: alicloud-nas
    size: 10Gi
  resources:
    requests:
      memory: 64Mi
      cpu: 10m
redis:
  persistence:
    storageClass: alicloud-nas
    size: 5Gi
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
gitlab:
  gitaly:
    persistence:
      storageClass: alicloud-nas
      size: 50Gi
  unicorn:
    minReplicas: 1
    resources:
      limits:
       memory: 1.5G
      requests:
        cpu: 100m
        memory: 900M
    workhorse:
      resources:
        limits:
          memory: 100M
        requests:
          cpu: 10m
          memory: 10M
  sidekiq:
    minReplicas: 1
    resources:
      limits:
        memory: 1.5G
      requests:
        cpu: 50m
        memory: 625M
  gitlab-shell:
    minReplicas: 1
  task-runner:
    enabled: false
registry:
  minReplicas: 1
certmanager:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
